version: "3"

services:
  node:
    image: node:16
    user: node
    working_dir: /app
    volumes:
      - ./:/app
    container_name: challenge_back_end
    tty: true
    stdin_open: true
    command: bash
    restart: always
    ports:
      - 3002:3001
